version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:jessie

    working_directory: /src/docker-elasticsearch-circleci

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Install Docker client
          environment:
            DOCKER_VERSION: "17.03.0-ce"
          command: |
            set -x
            curl -L -o /tmp/docker-$DOCKER_VERSION.tgz https://get.docker.com/builds/Linux/x86_64/docker-$DOCKER_VERSION.tgz
            tar -xz -C /tmp -f /tmp/docker-$DOCKER_VERSION.tgz
            mv /tmp/docker/* /usr/bin

      - run:
          name: Run A Container to check whether it successfully runs on CI
          environment:
            IMAGETAG: kenju/elasticsearch-circleci:test
          command: |
            docker build -t $IMAGETAG image/
            # run docker for development use
            #   https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-cli-run-dev-mode
            # here is why to set 'http.host' and 'transport.host'
            #   https://www.elastic.co/guide/en/elasticsearch/reference/5.3/bootstrap-checks.html#_development_vs_production_mode
            # docker run -d -p 9200:9200 -e "http.host=0.0.0.0" -e "transport.host=127.0.0.1" $IMAGETAG
            docker run -p 9200:9200 -e "http.host=0.0.0.0" -e "transport.host=127.0.0.1" $IMAGETAG

      - run:
          name: Install Health Check Utility
          command: |
            apt-get update -qq
            apt-get install -y netcat

      - run:
          name: Health Check Elasticsearch from primary_container
          environment:
            HEALTH_CHECK_RETRY_LIMIT: 20
            HEALTH_CHECK_RETRY_WAIT: 3
            HEALTH_CHECK_PORT: 9200
          command: |
            for i in $(seq $HEALTH_CHECK_RETRY_LIMIT); do
              nc -vz 127.0.0.1 $HEALTH_CHECK_PORT || (sleep $HEALTH_CHECK_RETRY_WAIT; false) && break
            done
