version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:jessie

    working_directory: /src/docker-elasticsearch-circleci

    environment:
      CONTAINER_NAME: es_container
      IMAGETAG: kenju/elasticsearch-circleci:test

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Install Docker client
          environment:
            DOCKER_VERSION: "17.03.0-ce"
          command: |
            set -x
            curl -L -o /tmp/docker-$DOCKER_VERSION.tgz https://get.docker.com/builds/Linux/x86_64/docker-$DOCKER_VERSION.tgz
            tar -xz -C /tmp -f /tmp/docker-$DOCKER_VERSION.tgz
            mv /tmp/docker/* /usr/bin

      - run:
          name: Build a docker image from Dockerfile
          command: docker build -t $IMAGETAG image/

      - run:
          name: Run a container from the image
          command: |
            # run docker for development use
            #   https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-cli-run-dev-mode
            # here is why to set 'http.host' and 'transport.host'
            #   https://www.elastic.co/guide/en/elasticsearch/reference/5.3/bootstrap-checks.html#_development_vs_production_mode
            docker run -d --name $CONTAINER_NAME -p 9200:9200 -e "http.host=0.0.0.0" -e "transport.host=127.0.0.1" $IMAGETAG

      - run: docker ps

      - run:
          name: Health Check Elasticsearch from primary_container
          environment:
            HEALTH_CHECK_RETRY_LIMIT: 20
            HEALTH_CHECK_RETRY_DELAY: 3
            HEALTH_CHECK_PORT: 9200
          command: |
            docker run --network container:$CONTAINER_NAME \
              appropriate/curl --retry $HEALTH_CHECK_RETRY_LIMIT \
                               --retry-delay $HEALTH_CHECK_RETRY_DELAY \
                               --retry-connrefused http://localhost:$HEALTH_CHECK_PORT
